
package pantallas;

import entidades.Curso;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class PantallaGestorCursos extends javax.swing.JFrame {

    /**
     * Creates new form PantallaGestorCuross
     */
    public PantallaGestorCursos(List<Curso> lista) {
        initComponents();
        this.ListaCurso = lista;
        llenarList();
        this.setLocationRelativeTo(null);

    }
    public static List<Curso> ListaCurso= new ArrayList<Curso>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_salir1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_cursos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txt_nombrebuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JLabel();
        btn_verProfesor = new javax.swing.JLabel();
        btn_verEstud = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JLabel();

        btn_salir1.setText("Ver Estudiantes");
        btn_salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        list_cursos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_cursos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 147, 342, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Gestor de Cursos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 25, -1, -1));

        txt_nombrebuscar.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombrebuscar.setForeground(new java.awt.Color(0, 0, 0));
        txt_nombrebuscar.setBorder(null);
        getContentPane().add(txt_nombrebuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 170, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Texbox.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 198, 38));

        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar.png"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, 58));

        btn_verProfesor.setForeground(new java.awt.Color(255, 255, 255));
        btn_verProfesor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_verProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Profesores.png"))); // NOI18N
        btn_verProfesor.setText("Profesores");
        btn_verProfesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_verProfesor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_verProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_verProfesorMouseClicked(evt);
            }
        });
        getContentPane().add(btn_verProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 40));

        btn_verEstud.setForeground(new java.awt.Color(255, 255, 255));
        btn_verEstud.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_verEstud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Profesores.png"))); // NOI18N
        btn_verEstud.setText("Estudiantes");
        btn_verEstud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_verEstud.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_verEstud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_verEstudMouseClicked(evt);
            }
        });
        getContentPane().add(btn_verEstud, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 112, 40));

        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Agregar.png"))); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, 40));

        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Eliminar.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void llenarList(){
        DefaultListModel modelo =new DefaultListModel();        
        list_cursos.setModel(modelo); 
        modelo.removeAllElements();
        for (int i = 0; i < ListaCurso.size(); i++) {
            modelo.addElement(ListaCurso.get(i).getCodigo()+"         "+
            ListaCurso.get(i).getNombre()+"          "
            +ListaCurso.get(i).getCreditos());
        }
    }    private static Curso curso = null;
    private void btn_salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salir1ActionPerformed

    private void btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseClicked
        // TODO add your handling code here:
        String nombrCurso = txt_nombrebuscar.getText();
        boolean encontrado = false;
        if(!nombrCurso.isEmpty())
        {
            for (int i = 0; i < ListaCurso.size(); i++) {
                if(ListaCurso.get(i).getNombre().equals(nombrCurso))
                {
                    encontrado= true;
                    llenarList();
                    this.curso=ListaCurso.get(i);
                    JOptionPane.showMessageDialog(null, "Curso Encontrado \n"
                        + "Codigo: "+ListaCurso.get(i).getCodigo()+"\n"
                        + "Nombre: "+ListaCurso.get(i).getNombre()+"\n"
                        + "Creditos: "+ListaCurso.get(i).getCreditos(),
                    "Eliminar", JOptionPane.INFORMATION_MESSAGE); 
                }
            }
            if(encontrado==false){
                 JOptionPane.showMessageDialog(null, "El curso ingresado no"
                         + " existe","Buscar", JOptionPane.INFORMATION_MESSAGE); 
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese nombre del curso",
                    "Buscar", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_btn_buscarMouseClicked

    private void btn_verProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verProfesorMouseClicked
        // TODO add your handling code here:
        
        if(this.curso!=null)
        {
            PantallaProfesores pantaVerProfe = new PantallaProfesores(this.curso);
            pantaVerProfe.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Primero debe buscar el curso",
                    "Ver Profesores", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_btn_verProfesorMouseClicked

    private void btn_verEstudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verEstudMouseClicked
         // TODO add your handling code here:
         if(this.curso!=null)
        {
            PantallaEstudiantes pantaVerEstu = new PantallaEstudiantes(this.curso);
            pantaVerEstu.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Primero debe buscar el curso",
                    "Ver Profesores", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_btn_verEstudMouseClicked

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        PantallaEditarCurso pantaEditCurs =new PantallaEditarCurso(ListaCurso);
        pantaEditCurs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        // TODO add your handling code here:
        String nombrCurso = txt_nombrebuscar.getText();
        boolean eliminado = false;
        if(!nombrCurso.isEmpty())
        {
            for (int i = 0; i < ListaCurso.size(); i++) {
                if(ListaCurso.get(i).getNombre().equals(nombrCurso))
                {
                    ListaCurso.remove(i);
                    eliminado= true;
                    llenarList();
                    JOptionPane.showMessageDialog(null, "Curso Eliminado",
                    "Eliminar", JOptionPane.INFORMATION_MESSAGE); 
                }
            }
            if(eliminado==false){
                 JOptionPane.showMessageDialog(null, "El curso ingresado no"
                         + " existe","Eliminar", JOptionPane.INFORMATION_MESSAGE); 
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese nombre del curso",
                    "Eliminar", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_btn_eliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaGestorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaGestorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaGestorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaGestorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaGestorCursos(ListaCurso).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_agregar;
    private javax.swing.JLabel btn_buscar;
    private javax.swing.JLabel btn_eliminar;
    private javax.swing.JButton btn_salir1;
    private javax.swing.JLabel btn_verEstud;
    private javax.swing.JLabel btn_verProfesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_cursos;
    private javax.swing.JTextField txt_nombrebuscar;
    // End of variables declaration//GEN-END:variables
}
