
package pantallas;

import entidades.Curso;
import entidades.Profesor;
import javax.swing.JOptionPane;


public class PantallaEditarProfesor extends javax.swing.JFrame {

    private Curso curso;
    
    
    /**
     * Creates new form PantallaEditarProfesor
     */
    public PantallaEditarProfesor( Curso curso) {
        initComponents();
        this.curso= curso;
        this.setLocationRelativeTo(null);
    }

    public void guardar(Profesor profesor ){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setText("[Nombre del Profesor]");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 39, -1, -1));

        txt_nombre.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombre.setForeground(new java.awt.Color(0, 0, 0));
        txt_nombre.setBorder(null);
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 249, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txtCursos.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 104, -1, 46));

        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Eliminar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 168, -1, 55));

        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Agregar.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 168, -1, 55));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
         this.dispose();
        PantallaProfesores pantprofe = new PantallaProfesores(curso);
        pantprofe.setVisible(true);
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        Profesor profe = new Profesor();
    if (!txt_nombre.getText().isEmpty()) {
        profe.setNombre(txt_nombre.getText());
        curso.agregarProfesor(profe);
        txt_nombre.setText("");
        
        // Después de guardar el profesor, regresar a PantallaProfesores
        this.dispose(); // Cierra la ventana actual
        PantallaProfesores pantprofe = new PantallaProfesores(curso);
        pantprofe.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(null, "Complete el campo nombre", "Agregar", JOptionPane.INFORMATION_MESSAGE); 
    }
    }//GEN-LAST:event_btn_guardarMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btn_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
