
package pantallas;

import entidades.Curso;
import entidades.Estudiante;
import static pantallas.PantallaGestorCursos.ListaCurso;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class PantallaEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form PantallaEstudiantes
     */
    private Curso curso;
    private Estudiante estudiante=null;
    public PantallaEstudiantes(Curso curso) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.curso= curso;
        txtNombredelcurso.setText(curso.getNombre()); 
        llenarList();
    }
    public void llenarList(){
        DefaultListModel modelo =new DefaultListModel();        
        list_estudiantes.setModel(modelo); 
        modelo.removeAllElements();
        for (int i = 0; i < curso.getEstudiantes().length; i++) {
            if(curso.getEstudiantes()[i]!=null){
                modelo.addElement(curso.getEstudiantes()[i].getNombre()
                        +"             "+
                        curso.getEstudiantes()[i].getCodigo());
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_estudiantes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txtNombredelcurso = new javax.swing.JLabel();
        txt_nombrebuscar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JLabel();
        btn_salir = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        list_estudiantes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_estudiantes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 160, 430, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Estudiantes de:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 29, -1, -1));

        txtNombredelcurso.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNombredelcurso.setText("[Nombre del curso]");
        getContentPane().add(txtNombredelcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 29, -1, -1));

        txt_nombrebuscar.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombrebuscar.setForeground(new java.awt.Color(0, 0, 0));
        txt_nombrebuscar.setBorder(null);
        getContentPane().add(txt_nombrebuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 249, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txtCursos.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 46));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txtCursos.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 46));

        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar.png"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Eliminar.png"))); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Agregar.png"))); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Eliminar.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseClicked
        String nombreEstudi = txt_nombrebuscar.getText();
        boolean encontrado = false;
        if(!nombreEstudi.isEmpty())
        {
            for (int i = 0; i < 30; i++) {
                if(curso.getEstudiantes()[i]!=null &&
                    curso.getEstudiantes()[i].getNombre().equals(nombreEstudi))
                {
                    encontrado= true;
                    llenarList();     
                    estudiante = curso.getEstudiantes()[i];
                    JOptionPane.showMessageDialog(null, "Estudiante Encontrado \n"                        
                        + "Nombre: "+curso.getEstudiantes()[i].getNombre()+"\n"
                        + "Codigo: "+curso.getEstudiantes()[i].getCodigo()+"\n",
                    "Buscar", JOptionPane.INFORMATION_MESSAGE); 
                }
            }
            if(encontrado==false){
                 JOptionPane.showMessageDialog(null, "El estudiante ingresado no"
                         + " esta registrado","Buscar", JOptionPane.INFORMATION_MESSAGE); 
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese nombre del estudiante",
                    "Buscar Profesor", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_btn_buscarMouseClicked

    private void btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseClicked
        // TODO add your handling code here:
        PantallaGestorCursos pantalla = new PantallaGestorCursos(ListaCurso);
        pantalla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_salirMouseClicked

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        // TODO add your handling code here:
         PantallaEditarEstudiante pantallaEditEstu = new PantallaEditarEstudiante(curso);
        pantallaEditEstu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_agregarMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        // TODO add your handling code here:
       boolean eliminado = false;
        Estudiante [] nuevalista = curso.getEstudiantes();
        if(estudiante!=null)
        {            
            for (int i = 0; i < 30; i++) {
                if(curso.getEstudiantes()[i]!=null&&
                        curso.getEstudiantes()[i].equals(estudiante))
                {
                    nuevalista[i]=null;
                    curso.setEstudiantes(nuevalista);
                    eliminado= true;
                    llenarList();
                    JOptionPane.showMessageDialog(null, "Estudiante Eliminado",
                    "Eliminar", JOptionPane.INFORMATION_MESSAGE); 
                }
            }
            if(eliminado==false){
                 JOptionPane.showMessageDialog(null, "El estudiante ingresado no"
                    + " esta registrado","Eliminar", JOptionPane.INFORMATION_MESSAGE); 
            }
        }else{
            JOptionPane.showMessageDialog(null, "Primero debes buscar mediante el nombre",
                    "Eliminar Estudiante", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_btn_eliminarMouseClicked

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_agregar;
    private javax.swing.JLabel btn_buscar;
    private javax.swing.JLabel btn_eliminar;
    private javax.swing.JLabel btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_estudiantes;
    private javax.swing.JLabel txtNombredelcurso;
    private javax.swing.JTextField txt_nombrebuscar;
    // End of variables declaration//GEN-END:variables
}
